[package]
name = "scriptx"
version = "0.1.0"
authors = ["Joel Montes de Oca <no-email>"]
edition = "2018"
description = "A program to cut verses from American Sign Language version of the New World Translation Bible."
readme = "README.md"
license = "GPL3.0"
license-file = "LICENSE.md"
keywords = ["cli", "nwt", "bible", "ffmpeg", "jehovah-witness"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
