name: Package deb file
on:
  push:
    tags:
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: stable
        
    - name: Build Release
      run: cargo build --release

    - name: Install help2man
      run: sudo apt install help2man

    - name: Create deb package
      run: ./make-deb

    - name: Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "/tmp/*.deb"
        tags: true
        draft: true